JhinQuotes = [
  "In carnage, I bloom, like a flower in the dawn.",
  "I have risen from the filth and muck. I am the lotus blossom. I am beauty.",
  "That delightful moment before the curtain goes up.",  
  "Our performance begins.",
  "The stage is set.",
  "I suppose I must make do with this tawdry setting.",
  "This stage is beneath my talent, but I shall elevate it.",
  "I will bring them an opera of death.",
  "And now, the curtain rises.",
  "The work is what matters.",
  "Art requires a certain cruelty.",
  "The end is important in all things.",
  "My audience awaits.",
  "I must wait until the composition is perfect.",
  "They're puppets. I pull their strings, and then they dance.",
  "My genius will be understood - eventually.",
  "Art must exist beyond reason.",
  "They call me mad. All artists are mad.",
  "I will not suffer this ugliness.",
  "I cannot be good. I must be perfection.",
  "Every element must be in place.",
  "I'm misunderstood. Beauty can't be evil.",
  "This performance needs more... zazz.",
  "It's so difficult to work under these conditions.",
  "My talent justifies all actions.",
  "I am at my best only during the performance.",
  "I am pure. My work is pure.",
  "My theater is the mind.",
  "Art should terrify.",
  "No poet's words could match my craft.",
  "Death should never be quick. It should be an opera.",
  "I shall choreograph this affair.",
  "What sweet sadness is killing?",
  "The world is cruel. It does not have to be ugly.",
  "Everyone wears a mask. I just chose to create my own.",
  "This art is a compulsion. I cannot resist it.",
  "Perfection isn't good enough.",
  "Behind every mask... is another mask.",
  "There is nothing for me but this.",
  "I never hurt anyone. It is the performance that kills.",
  "Until they stop me, I will keep going.",
  "I am the singer without a voice. The dancer without legs.",
  "Only to the audience do I show my true face.",
  "Each bullet is a piece of my soul. Each shot is a piece of me.",
  "I swear each performance is the last, but I lie every time.",
  "I am a slave to this passion.",
  "My work asks questions, it never has answers.",
  "Which is the lie? The mask, or my face?",
  "An icon doesn't have to explain himself.",
  "I wonder what they think when they see me.",
  "Yes, the gun is ironic.",
  "I like a violent composition.",
  "This would be easier if blood came in more colours.",
  "Let's start the show.",
  "The ecstasy of opening night.",
  "Smiles and screams, I bring both.",
  "If I keep getting interrupted, how can I be expected to work?",
  "I was paid to put on a killer show.",
  "My clients expect the best.",
  "They will dance, they will sing, they will die!",
  "A costume, some makeup, a spray of blood.",
  "It's very simple - when I shoot, they dance.",
  "My critics are... usually short-lived.",
  "If I get this outfit dirty, I'm going to be so annoyed.",
  "I serve a discerning clientele.",
  "Death is certain, but killing doesn't have to be ugly.",
  "I provide catharsis for my clients, and my victims.",
  "I... orchestrate death.",
  "I get nervous before every performance, but I need that feeling.",
  "The moment before the shot... is painful.",
  "It is only when the gun fires that I am alive.",
  "Mmm... the ecstasy of killing.",
  "The trigger on a loaded weapon... it whispers for us to act.",
  "I can't live without the euphoria of performance.",
  "Happiness... is a warm gun.",
  "I want to feel everything. The gun makes it so I do.",
  "I envy silence... because I must be loud.",
]